app1/urls.py
from django.conf.urls import patterns, include, url

from . import views

urlpatterns = patterns('',
    (r'^add/$', views.add_book.as_view()),
    (r'^$', views.show_books.as_view()),
    (r'^authors/$', views.show_authors.as_view()),
    (r'^search/$', views.search),

)

funds/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = patterns('',

    (r'^me/$', views.me),
    (r'^me/update/(?P<pk>\d+)$', login_required(views.me_update.as_view())),

    (r'^record/$', login_required(views.record.as_view())),
    (r'^record/assum/create/$', login_required(views.assum_create.as_view())),
    (r'^record/income/create/$', login_required(views.income_create.as_view())),
    (r'^record/other/create/$', login_required(views.other_create.as_view())),

    (r'^record/assum/$', login_required(views.assum.as_view())),
    (r'^record/income/$', login_required(views.income.as_view())),
    (r'^record/other/$', login_required(views.other.as_view())),

    (r'^record/assum/update/(?P<pk>\d+)$', login_required(views.assum_update.as_view())),
    (r'^record/income/update/(?P<pk>\d+)$', login_required(views.income_update.as_view())),
    (r'^record/other/update/(?P<pk>\d+)$', login_required(views.other_update.as_view())),

    (r'^account/$', login_required(views.account.as_view())),
    (r'^account/deposit/create/$', login_required(views.deposit_create.as_view())),
    (r'^account/loan/create/$', login_required(views.loan_create.as_view())),

    (r'^account/deposit/delete/(?P<pk>\w+)$', login_required(views.deposit_delete.as_view())),
    (r'^account/loan/delete/(?P<pk>\w+)$', login_required(views.loan_delete.as_view())),
    (r'^account/deposit/update/(?P<pk>\w+)$', login_required(views.deposit_update.as_view())),
    (r'^account/loan/update/(?P<pk>\w+)$', login_required(views.loan_update.as_view())),


)

mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from . import views
from .settings import STATICFILES_DIRS

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pro.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    (r'^accounts/login/$', views.login),
    (r'^accounts/logout/$', views.logout),
    (r'^accounts/changepw/$', views.changepw),
    (r'^home/$', views.home),

    url(r'^funds/', include('funds.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root':STATICFILES_DIRS}),
)

funds/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
SEX_CHOICES=(('Male','male'),('Female','female'))

#个人信息
class Me(models.Model):
    user = models.OneToOneField(User)
    realname = models.CharField(max_length=20,verbose_name="真实姓名",)
    sex = models.CharField(max_length=10,verbose_name="性别",
                           choices=SEX_CHOICES)
    birth = models.DateField(verbose_name="生日",)
    cash = models.FloatField(verbose_name="现金额",)

    def __unicode__(self):
        return u'%s %s'%(self.user, self.realname)

class Record(models.Model):
    ID = models.AutoField(primary_key=True)
    owner = models.ForeignKey(Me)
    date = models.DateField(verbose_name='时间')
    place = models.CharField(max_length=50,verbose_name='地点')

    class Meta:
        ordering = ['-date','ID']

    def __unicode__(self):
        return u'%d'%(self.ID)

#支出
class Assumption(Record):
    amount = models.FloatField(verbose_name='金额')
    items = models.CharField(max_length=50,verbose_name='条目')

    def __unicode__(self):
        return u'%s %s'%(self.date,self.items)

#收入
class Income(Record):
    amount = models.FloatField(verbose_name='金额')
    source = models.CharField(max_length=20,verbose_name='来源')

    def __unicode__(self):
        return u'%s %s'%(self.date,self.source)

#其他事务
class Other(Record):
    details = models.TextField(verbose_name='详细')

    def __unicode__(self):
        return u'%s %s'%(self.date,self.details)

#存款账户
class Deposit(models.Model):
    name = models.CharField(max_length=20,primary_key=True,verbose_name='账户名')
    owner = models.ForeignKey(Me)
    balance = models.FloatField(verbose_name='余额')
    deposit_type = models.CharField(max_length=20,verbose_name='账户类型')
    bank = models.CharField(max_length=20,verbose_name='银行')
    opening_date = models.DateField(verbose_name='开户日期')

    def __unicode__(self):
        return u'%s'%(self.name)

#贷款账户
class Loan(models.Model):
    name = models.CharField(max_length=20,primary_key=True,verbose_name='账户名')
    owner = models.ForeignKey(Me)
    amount = models.FloatField(verbose_name='金额')
    loan_type = models.CharField(max_length=20,verbose_name='账户类型')
    bank = models.CharField(max_length=20,verbose_name='银行')
    opening_date = models.DateField(verbose_name='贷款日期')

    def __unicode__(self):
        return u'%s'%(self.name)

funds/forms.py
#!/usr/bin/python
# coding:utf-8
from django import forms
from django.forms import widgets

class SearchForm(forms.Form):
    y = forms.DecimalField(required=True, widget=
        forms.TextInput(attrs={'placeholder':u"年份",'required':"required"}),)
    m = forms.DecimalField(required=True, widget=
        forms.TextInput(attrs={'placeholder':u"月份",'required':"required"}),)

    def clean(self):
        cleaned_data = super(SearchForm, self).clean()
        y=cleaned_data.get('y')#如果默认clean不通过，y为空值
        m=cleaned_data.get('m')
        if (y and int(y) < 1000) or (m and (int(m) < 1 or int(m) > 12)):
            raise forms.ValidationError("Invalid Input!")
        return cleaned_data

funds/views.py
#coding:utf8
from django.http import HttpResponseRedirect,HttpResponse,Http404
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView,CreateView,DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from .models import Me,Assumption,Income,Other,Record,Deposit,Loan
from .forms import SearchForm
# Create your views here.
@login_required
def me(request):
    user = Me.objects.get(user_id__exact=request.user.id)
    return render_to_response('me.html',{'me':user},context_instance=RequestContext(request))

class me_update(UpdateView):
    model = Me
    fields = ['realname','sex','birth']
    template_name = 'update.html'
    success_url = '/funds/me/'

    def get_object(self, queryset=None):
        obj = super(me_update, self).get_object()
        if not obj == Me.objects.get(user_id__exact=self.request.user.id):
            raise Http404('NO PERMISSION')
        return obj

##    def get(self, request, **kwargs):
##        self.object = Me.objects.get(user_id__exact=request.user.id)
##        form_class = self.get_form_class()
##        form = self.get_form(form_class)
##        context = self.get_context_data(object=self.object, form=form)
##        return self.render_to_response(context)

class record(ListView):
    queryset = []
    template_name = 'record.html'

    def get_context_data(self, **kwargs):
        context = super(record, self).get_context_data(**kwargs)
        u = Me.objects.get(user_id__exact=self.request.user.id)
        context['Income'] = Income.objects.filter(owner__exact=u)[0:10]
        context['Other'] = Other.objects.filter(owner__exact=u)[0:10]
        context['Assumption'] = Assumption.objects.filter(owner__exact=u)[0:10]
        return context

class assum_create(CreateView):
    model = Assumption
    template_name = 'create_assum.html'
    success_url = '/funds/record/'
    fields = ['date','place','amount','items']

    def form_valid(self, form):
        obj = form.save(commit=False)
        owner = Me.objects.get(user_id__exact=self.request.user.id)
        owner.cash -= obj.amount
        owner.save()
        obj.owner = owner
        obj.save()
        return HttpResponseRedirect(self.success_url)

class income_create(CreateView):
    model = Income
    template_name = 'create_income.html'
    success_url = '/funds/record/'
    fields = ['date','place','amount','source']

    def form_valid(self, form):
        obj = form.save(commit=False)
        owner = Me.objects.get(user_id__exact=self.request.user.id)
        owner.cash += obj.amount
        owner.save()
        obj.owner = owner
        obj.save()
        return HttpResponseRedirect(self.success_url)

class other_create(CreateView):
    model = Other
    template_name = 'create_other.html'
    success_url = '/funds/record/'
    fields = ['date','place','details']

    def form_valid(self, form):
        obj = form.save(commit=False)
        owner = Me.objects.get(user_id__exact=self.request.user.id)
        obj.owner = owner
        obj.save()
        return HttpResponseRedirect(self.success_url)

class assum(ListView):
    model = Assumption
    paginate_by = 15
    template_name = 'record_assum.html'

    def get_context_data(self, **kwargs):
        context = super(assum, self).get_context_data(**kwargs)
        if 'y' in self.request.GET:
            context['y']=self.request.GET['y']
        if 'm' in self.request.GET:
            context['m']=self.request.GET['m']
            form = SearchForm(self.request.GET)
            if not form.is_valid():
                context['err']=True
            else:
                queryset = context['object_list']
                s = 0
                for obj in queryset:
                    s+=obj.amount
                context['sum']=s
        else:
            form = SearchForm()
        context['searchform']=form
        return context

    def get_queryset(self):
        u = Me.objects.get(user_id__exact=self.request.user.id)
        form = SearchForm(self.request.GET)
        if form.is_valid():
            return Assumption.objects.filter(owner__exact=u,date__year= \
                form.cleaned_data['y'],date__month=form.cleaned_data['m'])
        return Assumption.objects.filter(owner__exact=u)


class income(ListView):
    model = Income
    paginate_by = 15
    template_name = 'record_income.html'

    def get_context_data(self, **kwargs):
        context = super(income, self).get_context_data(**kwargs)
        if 'y' in self.request.GET:
            context['y']=self.request.GET['y']
        if 'm' in self.request.GET:
            context['m']=self.request.GET['m']
            form = SearchForm(self.request.GET)
            if not form.is_valid():
                context['err']=True
            else:
                queryset = context['object_list']
                s = 0
                for obj in queryset:
                    s+=obj.amount
                context['sum']=s
        else:
            form = SearchForm()
        context['searchform']=form
        return context

    def get_queryset(self):
        u = Me.objects.get(user_id__exact=self.request.user.id)
        form = SearchForm(self.request.GET)
        if form.is_valid():
            return Income.objects.filter(owner__exact=u,date__year=form.cleaned_data['y'],\
                    date__month=form.cleaned_data['m'])
        return Income.objects.filter(owner__exact=u)

class other(ListView):
    model = Other
    paginate_by = 15
    template_name = 'record_other.html'

    def get_context_data(self, **kwargs):
        context = super(other, self).get_context_data(**kwargs)
        if 'y' in self.request.GET:
            context['y']=self.request.GET['y']
        if 'm' in self.request.GET:
            context['m']=self.request.GET['m']
            form = SearchForm(self.request.GET)
            if not form.is_valid():
                context['err']=True
        else:
            form = SearchForm()
        context['searchform']=form
        return context

    def get_queryset(self):
        u = Me.objects.get(user_id__exact=self.request.user.id)
        form = SearchForm(self.request.GET)
        if form.is_valid():
            return Other.objects.filter(owner__exact=u,date__year=form.cleaned_data['y'],\
                    date__month=form.cleaned_data['m'])
        return Other.objects.filter(owner__exact=u)

class deposit_create(CreateView):
    model = Deposit
    template_name = 'create_deposit.html'
    success_url = '/funds/account/'
    fields = ['name','balance','deposit_type','bank','opening_date']

    def form_valid(self, form):
        obj = form.save(commit=False)
        owner = Me.objects.get(user_id__exact=self.request.user.id)
        obj.owner = owner
        obj.save()
        return HttpResponseRedirect(self.success_url)

class loan_create(CreateView):
    model = Loan
    template_name = 'create_loan.html'
    success_url = '/funds/account/'
    fields = ['name','amount','loan_type','bank','opening_date']

    def form_valid(self, form):
        obj = form.save(commit=False)
        owner = Me.objects.get(user_id__exact=self.request.user.id)
        obj.owner = owner
        obj.save()
        return HttpResponseRedirect(self.success_url)

class account(ListView):
    queryset = []
    template_name = 'account.html'
    def get_context_data(self, **kwargs):
        context = super(account, self).get_context_data(**kwargs)
        u = Me.objects.get(user_id__exact=self.request.user.id)
        context['loan'] = Loan.objects.filter(owner__exact=u)
        context['deposit'] = Deposit.objects.filter(owner__exact=u)
        return context

class deposit_delete(DeleteView):
    model = Deposit
    template_name = 'delete_confirm.html'
    success_url = '/funds/account/'

    def get_object(self, queryset=None):
        obj = super(deposit_delete, self).get_object()
        if not obj.owner == Me.objects.get(user_id__exact=self.request.user.id):
            raise Http404('NO PERMISSION')
        return obj

class loan_delete(DeleteView):
    model = Loan
    template_name = 'delete_confirm.html'
    success_url = '/funds/account/'

    def get_object(self, queryset=None):
        obj = super(loan_delete, self).get_object()
        if not obj.owner == Me.objects.get(user_id__exact=self.request.user.id):
            raise Http404('NO PERMISSION')
        return obj

class deposit_update(UpdateView):
    model = Deposit
    fields = ['name','balance','deposit_type','bank','opening_date']
    template_name = 'update.html'
    success_url = '/funds/account/'

    def get_object(self, queryset=None):
        obj = super(deposit_update, self).get_object()
        if not obj.owner == Me.objects.get(user_id__exact=self.request.user.id):
            raise Http404('NO PERMISSION')
        return obj

class loan_update(UpdateView):
    model = Loan
    fields = ['name','amount','loan_type','bank','opening_date']
    template_name = 'update.html'
    success_url = '/funds/account/'

    def get_object(self, queryset=None):
        obj = super(deposit_update, self).get_object()
        if not obj.owner == Me.objects.get(user_id__exact=self.request.user.id):
            raise Http404('NO PERMISSION')
        return obj

class assum_update(UpdateView):
    model = Assumption
    template_name = 'update.html'
    success_url = '/funds/record/assum/'
    fields = ['date','place','amount','items']

    def get_object(self, queryset=None):
        obj = super(assum_update, self).get_object()
        if not obj.owner == Me.objects.get(user_id__exact=self.request.user.id):
            raise Http404('NO PERMISSION')
        return obj

class income_update(UpdateView):
    model = Income
    template_name = 'update.html'
    success_url = '/funds/record/income/'

funds/templates/account.html
{%extends "base.html"%}
{% block title %}我的银行账户{% endblock %}
{% block link %}
<link type="text/css" href="/static/tag.css" rel="stylesheet"/>
{%endblock%}
{}{}

{% block content %}
	<h1>我的银行账户</h1>
		<ul id="tabs">
			<li><a href="#" name="#tab1">存款账户</a></li>
			<li><a href="#" name="#tab2">贷款账户</a></li>
		</ul>
		<div id="content">
			<div id="tab1">
			{%if deposit%}
			{% for dep in deposit %}
				<table class="pure-table pure-table-striped">
					<tr>
						<label><th>账户名</th></label>
						<td>{{dep.name}}</td>
					</tr>
					<tr>
						<label><th>余额</th></label>
						<td>{{dep.balance}}</td>
					</tr>
					<tr>
						<th>账户类型</th>
						<td>{{dep.deposit_type}}</td>
					</tr>
					<tr>
						<th>银行</th>
						<td>{{dep.bank}}</td>
					</tr>
					<tr>
						<th>开户日期</th>
						<td>{{dep.opening_date|date:"Y-m-d"}}</td>
					</tr>
				</table>
				<a href="deposit/delete/{{dep.name}}" class="pure-button">删除账户</a>
				<a href="deposit/update/{{dep.name}}" class="pure-button">更新账户</a>
				<br />
			{%endfor%}
			{%else%}No Accounts!{%endif%}
			</div>
			<div id="tab2">
				{%if loan%}
				{% for dep in loan %}
				<table class="pure-table pure-table-striped">
					<tr>
						<label><th>账户名</th></label>
						<td>{{dep.name}}</td>
					</tr>
					<tr>
						<label><th>金额</th></label>
						<td>{{dep.amount}}</td>
					</tr>
					<tr>
						<th>账户类型</th>
						<td>{{dep.loan_type}}</td>
					</tr>
					<tr>
						<th>银行</th>
						<td>{{dep.bank}}</td>
					</tr>
					<tr>
						<th>贷款日期</th>
						<td>{{dep.opening_date|date:"Y-m-d"}}</td>
					</tr>
				</table>
				<a href="loan/delete/{{dep.name}}" class="pure-button">删除账户</a>
				<a href="loan/update/{{dep.name}}" class="pure-button">更新账户</a>
				<br />
				{%endfor%}
				{%else%}No Accounts!{%endif%}
			</div>
		</div>
  <script src="http://code.jquery.com/jquery-1.7.2.min.js"></script>

  <script>
    function resetTabs(){
        $("#content > div").hide(); //Hide all content
        $("#tabs a").attr("id",""); //Reset id's
    }

    var myUrl = window.location.href; //get URL
    var myUrlTab = myUrl.substring(myUrl.indexOf("#")); // For localhost/tabs.html#tab2, myUrlTab = #tab2
    var myUrlTabName = myUrlTab.substring(0,4); // For the above example, myUrlTabName = #tab

    (function(){
        $("#content > div").hide(); // Initially hide all content
        $("#tabs li:first a").attr("id","current"); // Activate first tab
        $("#content > div:first").fadeIn(); // Show first tab content

        $("#tabs a").on("click",function(e) {
            e.preventDefault();
            if ($(this).attr("id") == "current"){ //detection for current tab
             return
            }
            else{
            resetTabs();
            $(this).attr("id","current"); // Activate this
            $($(this).attr('name')).fadeIn(); // Show content for current tab
            }
        });

        for (i = 1; i <= $("#tabs li").length; i++) {
          if (myUrlTab == myUrlTabName + i) {
              resetTabs();
              $("a[name='"+myUrlTab+"']").attr("id","current"); // Activate url tab
              $(myUrlTab).fadeIn(); // Show url tab content
          }
        }
    })()
  </script>
	<!-- {%now "Y-m-d”%} -->

{% endblock %}

funds/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>{% block title %}{% endblock %}</title>
	<link type="text/css" href="/static/pure-customize.css" rel="stylesheet"/>
	<link href="/static/menu.css" rel="stylesheet" />
	{% block link %}{% endblock %}
	<script src="/static/Calendar.js" type="text/javascript"></script>
	<style>
		.container{margin:0px auto;width: 768px;background-color:Gainsboro;padding:12px}
		{% block style %}{%endblock %}
	</style>
</head>
<body>
	<nav>
		<ul>
			<li><a href="/home">主页</a></li>
			<li><a href="/funds/me/">{{user.username}}</a></li>
			<li><a href="#">添加记录</a>
				<ul>
					<li><a href="/funds/record/assum/create/">创建消费记录</a></li>
					<li><a href="/funds/record/income/create/">创建进账记录</a></li>
					<li><a href="/funds/record/other/create/">创建其他记录</a></li>
				</ul>
			</li>
			<li><a href="/funds/record/">事务记录</a>
				<ul>
					<li><a href="/funds/record/assum/">消费记录</a></li>
					<li><a href="/funds/record/income/">进账记录</a></li>
					<li><a href="/funds/record/other/">其他记录</a></li>
				</ul>
			</li>
			<li><a href="/funds/account/">银行账户</a>
				<ul>
					<li><a href="/funds/account/deposit/create/">增加存款账户</a></li>
					<li><a href="/funds/account/loan/create/">增加贷款账户</a></li>
				</ul>
			</li>
			<li><a href="/accounts/logout">注销</a></li>
			<li><a href="/admin">后台管理</a></li>
		</ul>
	</nav>

	<div class="container">
		{% block content %} {% endblock %}
	</div>
	<footer>

	</footer>
</body>

</html>

funds/templates/create_assum.html
{%extends "base.html"%}
{% block title %}创建消费记录{% endblock %}
{% block style %}th,td{padding:8px;}{% endblock %}

{% block content %}
	<h1>创建消费记录</h1>
	<form action="" method="post" class="pure-form">{% csrf_token %}
		<input type="button" class="pure-button" onclick="MyCalendar.SetDate(this,document.getElementById('id_date'))" value="Calender" />
		<table>
			{{form.as_table}}
		</table>
		<input type="submit" value="Create" class="pure-button" />
	</form>

{% endblock %}

funds/templates/create_deposit.html
{%extends "base.html"%}
{% block title %}添加存款账户{% endblock %}
{% block style %}th,td{padding:8px;}{% endblock %}

{% block content %}
	<h1>添加存款账户</h1>
	<form action="" method="post" class="pure-form">{% csrf_token %}
		<table>
			{{form.as_table}}
		</table>
		<input type="submit" value="Create" class="pure-button" />
		<input type="button" class="pure-button" onclick="MyCalendar.SetDate(this,document.getElementById('id_opening_date'))" value="Calender" />
	</form>
{% endblock %}

funds/templates/create_income.html
{%extends "base.html"%}
{% block title %}创建进账记录{% endblock %}
{% block style %}th,td{padding:8px;}{% endblock %}

{% block content %}
	<h1>创建进账记录</h1>
	<form action="" method="post" class="pure-form">{% csrf_token %}
		<input type="button" class="pure-button" onclick="MyCalendar.SetDate(this,document.getElementById('id_date'))" value="Calender" />
		<table>
			{{form.as_table}}
		</table>
		<input type="submit" value="Create" class="pure-button" />
	</form>

{% endblock %}

funds/templates/create_loan.html
{%extends "base.html"%}
{% block title %}添加贷款账户{% endblock %}
{% block style %}th,td{padding:8px;}{% endblock %}

{% block content %}
	<h1>添加贷款账户</h1>
	<form action="" method="post" class="pure-form">{% csrf_token %}
		<table>
			{{form.as_table}}
		</table>
		<input type="submit" value="Create" class="pure-button" />
		<input type="button" class="pure-button" onclick="MyCalendar.SetDate(this,document.getElementById('id_opening_date'))" value="Calender" />
	</form>
{% endblock %}

funds/templates/create_other.html
{%extends "base.html"%}
{% block title %}创建其他事务记录{% endblock %}
{% block style %}th,td{padding:8px;}{% endblock %}

{% block content %}
	<h1>创建其他事务记录</h1>
	<form action="" method="post" class="pure-form">{% csrf_token %}
		<input type="button" class="pure-button" onclick="MyCalendar.SetDate(this,document.getElementById('id_date'))" value="Calender" />
		<table>
		    {{form.as_table}}
		</table>
		<input type="submit" value="Create" class="pure-button"/>
	</form>

{% endblock %}

funds/templates/delete_confirm.html
{%extends "base.html"%}
{% block title %}{% endblock %}
{% block style %}p{font-size:18px;}.ul{position:relative;left:28px;}{% endblock %}

{% block content %}
<form action="" method="post" class="pure-form">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" class="pure-button"/>
</form>
{% endblock %}

funds/templates/me.html
{%extends "base.html"%}
{% block title %}个人信息{% endblock %}
{% block style %}{% endblock %}

{% block content %}
	<h1>我的信息</h1>
	{%if me%}
	<table class="pure-table pure-table-horizontal">
		<tr>
			<label><th>用户名</th></label>
			<td>{{me.user}}</td>
		</tr>
		<tr>
			<label><th>真实姓名</th></label>
			<td>{{me.realname}}</td>
		</tr>
		<tr>
			<th>性别</th>
			<td>{{me.sex}}</td>
		</tr>
		<tr>
			<th>生日</th>
			<td>{{me.birth|date:"Y-m-d"}}</td>
		</tr>
		<tr>
			<th>现金额</th>
			<td>￥{{me.cash}}</td>
		</tr>
		<tr>
			<th><a href="/funds/record/">事务记录</a></th>
			<td>{{me.record_set.count}}条记录</td>
		</tr>
		<tr>
			<th><a href="/funds/account/">银行账户</a></th>
			<td>{{me.deposit_set.count}}个存款账户<br/>{{me.loan_set.count}}个贷款账户</td>
		</tr>

	</table>
	<p><a href="update/{{me.user_id}}" class="pure-button">更新个人信息</a></p>
	<p><a href="/accounts/changepw" class="pure-button">修改密码</a></p>
	{%else%}	<p>Something Wrong!</p>
	{%endif%}

{% endblock %}

funds/templates/record_assum.html
{%extends "base.html"%}
{% block title %}消费记录{% endblock %}
{% block style %}{% endblock %}

{% block content %}
<h1>消费记录</h1>
	<div>
		<form action="" method="get" class="pure-form">
			{{searchform.as_table}}
			<input type="submit" value="GO" class="pure-button">
			{%if y and not err%}<a href="/funds/record/assum/">All Records</a>{%endif%}
		</form>
	</div>
{% if object_list %}
	<table class="pure-table pure-table-striped">
		<caption>{%if y and not err%}{{y}}年{{m}}月消费记录-合计{{sum}}元{%endif%}</caption>
		<thead>
			<tr>
				<th>时间</th>
				<th>地点</th>
				<th>金额</th>
				<th>条目</th>
			</tr>
		</thead>
		<tbody>
			{% for rd in object_list %}
			<tr>
				<td>{{rd.date|date:"Y-m-d"}}</td>
				<td><a href="update/{{rd.ID}}">{{rd.place}}</a></td>
				<td>{{rd.amount}}</td>
				<td>{{rd.items}}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% if is_paginated %}
	<p><ul class="pure-paginator">
		{% if page_obj.has_previous %}
		<li><a class="pure-button prev" href="?{%if y%}y={{y}}&m={{m}}&{%endif%}page={{ page_obj.previous_page_number}}">&#171;</a></li>
		{% endif %}
		{% for page_number in page_obj.paginator.page_range %}
			{% ifequal page_number page_obj.number %}
				<li><a class="pure-button pure-button-active">{{ page_number }}</a></li>
			{% else %}
				<li><a class="pure-button" href="?{%if y%}y={{y}}&m={{m}}&{%endif%}page={{page_number}}">{{ page_number }}</a></li>
			{% endifequal %}
		{% endfor %}
		{% if page_obj.has_next %}
		<li><a class="pure-button next" href="?{%if y%}y={{y}}&m={{m}}&{%endif%}page={{page_obj.next_page_number}}">&#187;</a></li>
		{% endif %}
	</ul></p>
	{% endif %}
{% else %}
	<p> No Records! </p>
{%endif%}
{% endblock %}

funds/templates/update.html
{%extends "base.html"%}
{% block title %}{% endblock %}
{% block style %}th,td{padding:8px;}{% endblock %}

{% block content %}
	<h1>修改信息</h1>
	<form action="" method="post" class="pure-form">{% csrf_token %}
		<table>{{ form.as_table }}</table>
		<input type="submit" value="Update" class="pure-button"/>
	</form>
	<!-- <p>user:{{me.sex}}</p> -->
	<!-- <p>user:{{object.user.username}}</p> -->
{% endblock %}